# Cloudflare Workers / D1 Deployment
# ----------------------------------
# This project uses Cloudflare D1 (SQLite) and R2 (Object Storage).
# A local database container (like Mongo or Postgres) is NO LONGER REQUIRED.
#
# To run the project locally:
#   pnpm dev
#
# To manage migrations:
#   pnpm migrate:create
#   pnpm migrate:run
#
# To deploy:
#   pnpm deploy
